# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.srcs/sources_1/new/logical_1bit.sv}
  {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.srcs/sources_1/new/b_gen.sv}
  {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.srcs/sources_1/new/mux2to1.sv}
  {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.srcs/sources_1/new/carry_gen.sv}
  {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.srcs/sources_1/new/fulladder.sv}
  {C:/Users/Bschnedar/Downloads/alu_128bit (1)/alu_128bit/alu_128bit.srcs/sources_1/new/alu_1bit.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top alu_1bit -part xc7a35tcpg236-1


write_checkpoint -force -noxdef alu_1bit.dcp

catch { report_utilization -file alu_1bit_utilization_synth.rpt -pb alu_1bit_utilization_synth.pb }
